// seed.ts — the §5.4-TWIN / legacy-test seed factory (pure). PURE: no Svelte import (CORE-02).
//
// PHASE 8 SPLIT (LOAD-05): the PLAYER-FACING starter board now lives in
// `src/lib/scenarios/starter.ts` (`starterScenario(): PersistedGame`) — a CLEAN turn-0
// PersistedGame loaded through the unified `loadGameState` path. `seedStarter()` here is
// RETAINED as the §5.4-TWIN: a turn-3, mid-engagement GameState whose baked turn-2 frag
// expend makes the §5.4 `frag → 2` numbers reproducible. THREE test suites still import it
// (reload-continuity, boot-resilience, seed-insecure-context — RESEARCH Runtime Inventory:
// do not silently break them), so it stays exported. `game.svelte.ts` no longer imports it
// for the player path — boot() loads `starterScenario()` instead.
//
// `seedStarter()` returns the §5.4-compatible "state before" as a complete,
// type-valid two-side GameState: BLUE {1-1 rifle-squad, MTR mortar-section} vs
// RED {DEF defenders}, at meta.turn 3 (the engagement is resolved ON turn 4).
//
// It MIRRORS the shape of the engine fixture `stateBefore_5_4()` (under the test
// tree) — but authors a PARALLEL object and imports NOTHING from the test tree
// (CORE-02 / threat T-05-01: app code never imports a test fixture). The
// §5.4 fixture stays the test's contract of record; this is the app-side twin so
// the worked example round-trips against the seeded game (the natural E2E fixture).
//
// CRITICAL invariant: BLUE.consumables.expended carries the PRIOR turn-2 frag
// expend `{ turn: 2, item: 'frag', qty: 2, actor: '1-1', reason: 'turn-2 contact' }`.
// Without it `remaining('frag', BLUE)` derives to 4 pre-turn and only reaches 4
// post-turn — NOT 2 — making the §5.4 `frag → 2` gate unsatisfiable. It is not
// optional: it is the reason the §5.4 result is reachable (6 − 2(turn2) − 2(turn4) = 2).
// smoke appears in NO expend entry, so remaining('smoke', BLUE) stays 4 (the canary).
//
// It is a FACTORY, not a shared constant: every call returns deep-distinct objects
// (incl. a fresh-cloned `expended` array) so a boot mutating one game never touches
// another — mirroring the fixture's factory discipline.

import type { GameState, Unit } from './engine/state';

/**
 * An insecure-context-safe unique id for `campaignName` (mirrors the guarded
 * `crypto.randomUUID` pattern at idb-save-store.ts:422-425). `crypto.randomUUID()`
 * is ONLY defined in a SECURE context (https / localhost); on a phone hitting the
 * app over plain `http://` (Tailscale IP / LAN) it is `undefined`, so a bare call
 * THREW and left boot's seed branch crashing — the real device bug this fixes.
 *
 * Order of preference:
 *   1. `crypto.randomUUID()` when it is a function (secure context — the ideal id).
 *   2. `crypto.getRandomValues(new Uint8Array(16))` mapped to a 32-char hex string —
 *      `getRandomValues` IS available in an insecure context (engine/dice.ts already
 *      relies on it for neutral entropy), so this is the actual fix.
 *   3. A last-resort non-crypto `${Date.now()}-${Math.random()…}` if `crypto` is
 *      entirely absent (never expected in a browser, but keeps seedStarter total).
 *
 * `crypto.getRandomValues` is an allowed platform global (CORE-02) — seed.ts imports
 * NOTHING from Svelte / idb / valibot and stays pure.
 *
 * PHASE 8: now EXPORTED so the bridge (`game.svelte.ts`) mints the stable `campaignId`
 * from the SAME insecure-context-safe helper (D-05 — the id is generated by boot, never
 * derived from `meta.campaignName`); single-sourcing it keeps the proven device guard in
 * one place rather than re-implementing a bare `crypto.randomUUID()` at the call site.
 */
export function randomId(): string {
	if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
		return crypto.randomUUID();
	}
	if (typeof crypto !== 'undefined' && typeof crypto.getRandomValues === 'function') {
		const bytes = crypto.getRandomValues(new Uint8Array(16));
		return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
	}
	return `${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

/**
 * A complete, type-valid Unit with §5.4-irrelevant fields as valid defaults
 * (mirrors the fixture's `makeUnit` defaulting — a PARALLEL author, not an import).
 */
export function makeUnit(over: Partial<Unit> & Pick<Unit, 'id' | 'type'>): Unit {
	return {
		strength: 100,
		morale: 'steady',
		supply: { ammo: 'high', fuel: 'high', rations: 'high', medical: 'high' },
		position: 'unknown',
		posture: 'staged',
		status: [],
		...over
	};
}

/**
 * The starter scenario — turn 3, the engagement about to be resolved on turn 4.
 *
 * BLUE loadout: frag 6, smoke 4, mortar_60mm 12, WITH the prior turn-2 frag expend
 * already materialized in `expended` (so remaining('frag') = 6 − 2 − 2 = 2 after the
 * turn-4 frag expend; smoke stays 4 — the canary). RED loadout: rpg 8, no prior expend.
 *
 * A fresh `campaignName` per call (`randomId()`, an insecure-context-safe id —
 * see the helper above) keeps every booted game distinct; the structure otherwise
 * matches the §5.4 "state before" verbatim so applying `EXAMPLE_ENVELOPE_5_4`
 * reproduces the §5.4 numbers.
 */
export function seedStarter(): GameState {
	return {
		meta: {
			campaignName: `starter-${randomId()}`,
			turn: 3,
			clock: 'D1 0700',
			weather: 'clear',
			terrain: 'urban',
			phase: 'engagement'
		},
		sides: [
			{
				id: 'BLUE',
				commander: 'player',
				objectives: ['seize objective ALPHA'],
				manifest: {
					doctrine: 'combined-arms',
					echelon: 'platoon',
					// organicAssets are CAPABILITIES, not unit IDs (spec §5.4) — the capability
					// gate (VALID-01) validates `capabilitiesUsed` against these, so the §5.4
					// assault (small_arms, frag) must find them here.
					organicAssets: ['small_arms', 'frag', 'smoke', 'mortar_60mm', 'at4', 'm240'],
					supportingAssets: ['60mm support'],
					prohibited: ['cas', 'artillery_beyond_60mm']
				},
				consumables: {
					loadout: { frag: 6, smoke: 4, mortar_60mm: 12 },
					// PRIOR turn-2 frag expend — so remaining('frag') = 6 − 2(turn2) − 2(turn4) = 2.
					expended: [{ turn: 2, item: 'frag', qty: 2, actor: '1-1', reason: 'turn-2 contact' }],
					resupplied: []
				},
				units: [
					makeUnit({ id: '1-1', type: 'rifle-squad', posture: 'staged' }),
					makeUnit({ id: 'MTR', type: 'mortar-section', posture: 'staged' })
				]
			},
			{
				id: 'RED',
				commander: 'ai',
				objectives: ['hold the strongpoint'],
				manifest: {
					doctrine: 'positional-defense',
					echelon: 'platoon',
					organicAssets: ['small_arms', 'rpg', 'pkm'],
					supportingAssets: [],
					prohibited: ['heavy_weapons']
				},
				consumables: {
					loadout: { rpg: 8 },
					expended: [],
					resupplied: []
				},
				units: [makeUnit({ id: 'DEF', type: 'defenders', posture: 'prepared' })]
			}
		],
		intel: { knows: {}, unconfirmedReports: [] },
		graveyard: [],
		// Phase 6 Slice A (UI-06): empty display-only narrative scrollback (mirrors
		// graveyard: []). Folded from `narrative` events; ZERO ledger authority.
		narrativeLog: []
	};
}
